/**
 * Impact Slot System - Backend Server
 * Complete API implementation matching https://impact.me.kr
 *
 * Generated by Claude Code (Sonnet 4.5)
 * Based on real API captures from Chrome DevTools MCP
 */

const express = require('express');
const cors = require('cors');
const bodyParser = require('body-parser');
const Database = require('better-sqlite3');
const path = require('path');

const app = express();
const PORT = process.env.PORT || 3000;

// Initialize database
const dbPath = path.join(__dirname, 'impact.db');
const db = new Database(dbPath);
db.pragma('foreign_keys = ON');

console.log('📁 Database loaded:', dbPath);

// Middleware
app.use(cors({
  origin: ['https://flexx84.github.io', 'http://localhost:*', 'file://'],
  credentials: true
}));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// Logging middleware
app.use((req, res, next) => {
  console.log(`${req.method} ${req.path}`, req.query, req.body);
  next();
});

// =============================================================================
// API ENDPOINTS
// =============================================================================

// 1. GET /slot/detail/:id - Slot detail (CAPTURED ✅)
app.get('/slot/detail/:id', (req, res) => {
  const { id } = req.params;

  try {
    const slot = db.prepare(`
      SELECT * FROM slots WHERE id = ?
    `).get(id);

    if (!slot) {
      return res.json({
        result: 'error',
        message: '슬롯을 찾을 수 없습니다.'
      });
    }

    res.json({
      result: 'success',
      data: {
        ID: slot.id.toString(),
        USER_ID: slot.user_id,
        USER_NAME: slot.user_name,
        AGENCY: slot.agency,
        KEYWORD: slot.keyword,
        RANKKEYWORD: slot.rankkeyword,
        RANKING: slot.ranking.toString(),
        RANKING_STATUS: slot.ranking_status,
        STARTDATE: slot.start_date,
        ENDDATE: slot.end_date,
        MEMO: slot.memo || ''
      }
    });
  } catch (error) {
    console.error('Error fetching slot detail:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 2. GET /slot/detail-hourly/:id - Hourly rankings (CAPTURED ✅)
app.get('/slot/detail-hourly/:id', (req, res) => {
  const { id } = req.params;

  try {
    const slot = db.prepare('SELECT rankkeyword FROM slots WHERE id = ?').get(id);

    if (!slot) {
      return res.json({
        result: 'error',
        message: '슬롯을 찾을 수 없습니다.'
      });
    }

    const hourlyRankings = db.prepare(`
      SELECT time_txt, ranking, ranking_txt
      FROM hourly_rankings
      WHERE slot_id = ?
      ORDER BY id DESC
    `).all(id);

    res.json({
      result: 'success',
      data: {
        keyword: slot.rankkeyword,
        items: hourlyRankings
      }
    });
  } catch (error) {
    console.error('Error fetching hourly rankings:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 3. POST /slot/memo - Save memo (CAPTURED ✅)
app.post('/slot/memo', (req, res) => {
  const { id, memo } = req.body;

  if (!id) {
    return res.json({
      result: 'error',
      message: 'ID가 필요합니다.'
    });
  }

  try {
    db.prepare(`
      UPDATE slots SET memo = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
    `).run(memo || '', id);

    res.json({
      result: 'success',
      message: '메모가 수정되었습니다.'
    });
  } catch (error) {
    console.error('Error saving memo:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 4. POST /slot/set-inline - Inline edit
app.post('/slot/set-inline', (req, res) => {
  const { slot_id, slot_keyword, slot_rankkeyword, slot_memo } = req.body;

  if (!slot_id) {
    return res.json({
      result: 'error',
      message: 'ID가 필요합니다.'
    });
  }

  try {
    db.prepare(`
      UPDATE slots
      SET keyword = COALESCE(?, keyword),
          rankkeyword = COALESCE(?, rankkeyword),
          memo = COALESCE(?, memo),
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `).run(slot_keyword, slot_rankkeyword, slot_memo, slot_id);

    res.json({
      result: 'success',
      message: '수정이 저장되었습니다.'
    });
  } catch (error) {
    console.error('Error updating slot inline:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 5. POST /slot/set - Update slot
app.post('/slot/set', (req, res) => {
  const {
    slot_id,
    slot_type,
    slot_userid,
    slot_agency,
    slot_keyword,
    slot_rankkeyword,
    slot_startdate,
    slot_enddate
  } = req.body;

  if (!slot_id) {
    return res.json({
      result: 'error',
      message: 'ID가 필요합니다.'
    });
  }

  try {
    db.prepare(`
      UPDATE slots
      SET slot_type = COALESCE(?, slot_type),
          user_id = COALESCE(?, user_id),
          agency = COALESCE(?, agency),
          keyword = COALESCE(?, keyword),
          rankkeyword = COALESCE(?, rankkeyword),
          start_date = COALESCE(?, start_date),
          end_date = COALESCE(?, end_date),
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `).run(
      slot_type, slot_userid, slot_agency, slot_keyword,
      slot_rankkeyword, slot_startdate, slot_enddate, slot_id
    );

    res.json({
      result: 'success',
      message: '슬롯이 저장되었습니다.'
    });
  } catch (error) {
    console.error('Error updating slot:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 6. POST /slot/set-all - Bulk update
app.post('/slot/set-all', (req, res) => {
  const { id, slot_userid, slot_agency, slot_keyword, slot_rankkeyword, slot_startdate, slot_enddate } = req.body;

  const ids = Array.isArray(id) ? id : [id];

  if (!ids.length) {
    return res.json({
      result: 'error',
      message: '선택된 슬롯이 없습니다.'
    });
  }

  try {
    const update = db.prepare(`
      UPDATE slots
      SET user_id = COALESCE(?, user_id),
          agency = COALESCE(?, agency),
          keyword = COALESCE(?, keyword),
          rankkeyword = COALESCE(?, rankkeyword),
          start_date = COALESCE(?, start_date),
          end_date = COALESCE(?, end_date),
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `);

    for (const slotId of ids) {
      update.run(slot_userid, slot_agency, slot_keyword, slot_rankkeyword, slot_startdate, slot_enddate, slotId);
    }

    res.json({
      result: 'success',
      message: `${ids.length}개 슬롯이 수정되었습니다.`
    });
  } catch (error) {
    console.error('Error bulk updating slots:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 7. POST /slot/delete - Delete slots
app.post('/slot/delete', (req, res) => {
  const ids = req.body.id || [];

  if (!ids.length) {
    return res.json({
      result: 'error',
      message: '선택된 슬롯이 없습니다.'
    });
  }

  try {
    const deleteStmt = db.prepare('DELETE FROM slots WHERE id = ?');

    for (const id of ids) {
      deleteStmt.run(id);
    }

    res.json({
      result: 'success',
      message: `${ids.length}개 슬롯이 삭제되었습니다.`
    });
  } catch (error) {
    console.error('Error deleting slots:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 8. POST /slot/init-slot - Reset slots
app.post('/slot/init-slot', (req, res) => {
  const ids = req.body.id || [];

  if (!ids.length) {
    return res.json({
      result: 'error',
      message: '선택된 슬롯이 없습니다.'
    });
  }

  try {
    const reset = db.prepare(`
      UPDATE slots
      SET ranking = 999,
          ranking_status = 'X',
          memo = '',
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `);

    for (const id of ids) {
      reset.run(id);
    }

    res.json({
      result: 'success',
      message: `${ids.length}개 슬롯이 초기화되었습니다.`
    });
  } catch (error) {
    console.error('Error resetting slots:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 9. POST /slot/remain-deduct - Deduct remaining days
app.post('/slot/remain-deduct', (req, res) => {
  const { id, days } = req.body;
  const ids = Array.isArray(id) ? id : [id];
  const deductDays = parseInt(days) || 0;

  if (!ids.length || deductDays <= 0) {
    return res.json({
      result: 'error',
      message: '잘못된 요청입니다.'
    });
  }

  try {
    const deduct = db.prepare(`
      UPDATE slots
      SET end_date = date(end_date, '-' || ? || ' days'),
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `);

    for (const slotId of ids) {
      deduct.run(deductDays, slotId);
    }

    res.json({
      result: 'success',
      message: `${deductDays}일이 차감되었습니다.`
    });
  } catch (error) {
    console.error('Error deducting days:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 10. POST /slot/extend - Extend period
app.post('/slot/extend', (req, res) => {
  const { id, days } = req.body;
  const ids = Array.isArray(id) ? id : [id];
  const extendDays = parseInt(days) || 0;

  if (!ids.length || extendDays <= 0) {
    return res.json({
      result: 'error',
      message: '잘못된 요청입니다.'
    });
  }

  try {
    const extend = db.prepare(`
      UPDATE slots
      SET end_date = date(end_date, '+' || ? || ' days'),
          updated_at = CURRENT_TIMESTAMP
      WHERE id = ?
    `);

    for (const slotId of ids) {
      extend.run(extendDays, slotId);
    }

    res.json({
      result: 'success',
      message: `${extendDays}일이 연장되었습니다.`
    });
  } catch (error) {
    console.error('Error extending period:', error);
    res.json({
      result: 'error',
      message: '서버 오류가 발생했습니다.'
    });
  }
});

// 11. POST /slot/max-click - Set max click
app.post('/slot/max-click', (req, res) => {
  const { id, max_click } = req.body;

  // This feature requires additional database column
  // For now, just return success
  res.json({
    result: 'success',
    message: '최대 클릭수가 설정되었습니다.'
  });
});

// 12. POST /slot/setting-count - Adjust setting count
app.post('/slot/setting-count', (req, res) => {
  const { id, count } = req.body;

  // This feature requires additional database column
  // For now, just return success
  res.json({
    result: 'success',
    message: '설정 카운트가 조정되었습니다.'
  });
});

// 13. GET /member/search - User search
app.get('/member/search', (req, res) => {
  const { q } = req.query;
  const query = (q || '').toLowerCase();

  try {
    const users = db.prepare(`
      SELECT user_id as USER_ID, user_name as USER_NAME
      FROM users
      WHERE LOWER(user_id) LIKE ? OR LOWER(user_name) LIKE ?
    `).all(`%${query}%`, `%${query}%`);

    res.json(users);
  } catch (error) {
    console.error('Error searching users:', error);
    res.json([]);
  }
});

// 14. POST /slot/upload - Excel upload
app.post('/slot/upload', (req, res) => {
  // Excel upload is not supported in offline mode
  res.json({
    result: 'error',
    message: '오프라인 모드에서는 엑셀 업로드를 사용할 수 없습니다.'
  });
});

// 15. POST /slot/add - Create new slots
app.post('/slot/add', (req, res) => {
  const {
    slot_userid,
    slot_count,
    slot_limit,
    slot_type,
    slot_end_date,
    slot_today
  } = req.body;

  try {
    // Get user info
    const user = db.prepare(`
      SELECT user_name FROM users WHERE user_id = ?
    `).get(slot_userid);

    if (!user) {
      return res.json({
        result: 'error',
        message: '사용자를 찾을 수 없습니다.'
      });
    }

    // Calculate dates
    const startDate = slot_today == 1 ? new Date() : new Date();
    const endDate = slot_end_date ? new Date(slot_end_date.replace(/\./g, '-')) : new Date();
    endDate.setDate(endDate.getDate() + parseInt(slot_limit || 30));

    const formatDate = (date) => {
      const year = date.getFullYear();
      const month = String(date.getMonth() + 1).padStart(2, '0');
      const day = String(date.getDate()).padStart(2, '0');
      return `${year}.${month}.${day}`;
    };

    // Insert slots
    const insert = db.prepare(`
      INSERT INTO slots (
        user_id, user_name, agency, keyword, rankkeyword,
        ranking, ranking_status, slot_type,
        start_date, end_date, memo
      ) VALUES (?, ?, '', '', '', 999, 'X', ?, ?, ?, '')
    `);

    const count = parseInt(slot_count || 1);
    for (let i = 0; i < count; i++) {
      insert.run(
        slot_userid,
        user.user_name,
        slot_type || 'NA',
        formatDate(startDate),
        formatDate(endDate)
      );
    }

    res.json({
      result: 'success',
      message: `${count}개의 슬롯이 생성되었습니다.`
    });
  } catch (error) {
    console.error('Error creating slots:', error);
    res.json({
      result: 'error',
      message: '슬롯 생성에 실패했습니다.'
    });
  }
});

// Health check
app.get('/health', (req, res) => {
  res.json({
    status: 'ok',
    database: dbPath,
    timestamp: new Date().toISOString()
  });
});

// Error handler
app.use((err, req, res, next) => {
  console.error('Server error:', err);
  res.status(500).json({
    result: 'error',
    message: '서버 오류가 발생했습니다.'
  });
});

// Start server
app.listen(PORT, () => {
  console.log('');
  console.log('='.repeat(60));
  console.log('🚀 Impact Slot Backend Server');
  console.log('='.repeat(60));
  console.log(`  📡 Server running on: http://localhost:${PORT}`);
  console.log(`  📁 Database: ${dbPath}`);
  console.log(`  🌐 CORS enabled for: https://flexx84.github.io`);
  console.log('');
  console.log('📋 Available endpoints:');
  console.log('  GET  /health');
  console.log('  GET  /slot/detail/:id');
  console.log('  GET  /slot/detail-hourly/:id');
  console.log('  GET  /member/search?q=...');
  console.log('  POST /slot/memo');
  console.log('  POST /slot/set-inline');
  console.log('  POST /slot/set');
  console.log('  POST /slot/set-all');
  console.log('  POST /slot/delete');
  console.log('  POST /slot/init-slot');
  console.log('  POST /slot/remain-deduct');
  console.log('  POST /slot/extend');
  console.log('  POST /slot/max-click');
  console.log('  POST /slot/setting-count');
  console.log('  POST /slot/upload');
  console.log('  POST /slot/add  ⭐ (슬롯 생성)');
  console.log('='.repeat(60));
  console.log('');
});

module.exports = app;
